version: '3.8'

services:
  web-production:
    image: ghcr.io/adminvpshub/do-cu-binh-van:latest
    ports:
      - "3009:3009"
    restart: unless-stopped
    environment:
      - PORT=3009
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
