version: '3.8'

services:
  web-local:
    build:
      context: .
      target: dev
    ports:
      - "3011:3011"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=3011
      - NODE_ENV=development
      - TZ=Asia/Ho_Chi_Minh
