DEPLOY_PATH/logs/client-ip-table-secret {
    size 10M
    rotate 7
    compress
    dateext
    missingok
    notifempty
    postrotate
        docker exec $(docker ps -q --filter name=web-production 2>/dev/null) nginx -s reopen 2>/dev/null || true
    endscript
}
