# Map ISO 8601 to YYYY-MM-DD HH:mm:ss
map $time_iso8601 $time_formatted {
    "~^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2})" "$1 $2";
}

# Log format: Custom datetime and real client IP
log_format cf_ip '$time_formatted;$http_cf_connecting_ip';
